[package]
name = "blinkies"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7.5"
embedded-hal = "1.0.0"
microbit-v2 = "0.15.1"
nrf52833-hal = "0.18.0"
nrf52833-pac = { version = "0.12.2", features = ["cortex-m-rt"] }
panic-halt = "1.0.0"

[dependencies.cortex-m]
version = "0.7.7"
features = ["inline-asm"]
