[package]
name = "mb2_hello"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
nrf52833-hal = "0.18.0"
panic-rtt-target = "0.2.0"
rtt-target = "0.6.1"
